apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-syji
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0043-tenant/tkrw-pr712-0075-0043-app/devfile-sample-syji@sha256:6aa838508e23f0ba1b1025dbd9d022f2ab57f9664c9c252576c59335269337cc
        name: my-nodejs
        resources: {}
status: {}
